### ISSUE TITLE
2.0.1 seems broken?

### ISSUE THREAD

**Issue by mrjmd** [mongkuen/gatsby-plugin-eslint#5]
Adding the gatsby-plugin-eslint to a brand new gatsby v2 project seems to fail currently. I was trying to add this to an existing project and it was failing, so I tried it out with a fresh install and had the same issue. Steps to reproduce:

- `gatsby new projectname` (build new gatsby project with latest default starter, currently that's giving me gatsby 2.0.4)
- `gatsby develop` (everything loads fine)
- `npm i --save-dev gatsby-plugin-eslint` (currently adds v 2.0.1)
- `npm install --save-dev eslint eslint-loader`
- add the default config in gatsby-config.js to plugins - `'gatsby-plugin-eslint',`
- `gatsby develop`

This produces the errors in the screenshot below:

![screen shot 2018-09-19 at 9 51 11 am](https://user-images.githubusercontent.com/2111857/45768388-93717980-bbf1-11e8-94a4-e9ee3a36ced5.png)

**Comment by mrjmd** [comment]
Possibly related: https://github.com/webpack-contrib/eslint-loader/issues/209

**Comment by JustFly1984** [comment]
Please update to support eslint 5

**Comment by mongkuen** [comment]
I'll be updating to eslint 5 shortly, finally getting around to things

But this error specifically is "No ESLint configuration found" because there is no `.eslintrc` file found. 

You can fix it by just dropping an empty `.eslintrc` file in the project root. 

I added more details into the readme instructions
